name = "Flydigi Apex 2 (Wireless)"
type = "gamepad"

[remap]
# Sticks
JoyZ = "CamX"
CamZ = "CamY"

# Wheel
Brake = "ActionWheelX"
Gas = "ActionWheelY"

# Dpad
PovUp = "Up"
PovDown = "Down"
PovLeft = "Left"
PovRight = "Right"

# Face buttons flipped in function
ActionV = "ActionH"
ActionH = "ActionV"
PinkyRight = "ActionC"
11 = "ActionD"

# Rear buttons
15 = "ActionL" # Left Nub, diagonally between and bumpers
14 = "ActionR" # Right Nub

# Underside
13 = "PinkyLeft" # Left Grip
12 = "PinkyRight" # Right Grip
ActionD = "PaddleLeft" # Left Under
ActionC = "PaddleRight" # Right Under
